---
apiVersion: v1
kind: Service
metadata:
  name: toposervice
  labels:
    app: toposervice
spec:
  type: ClusterIP
  selector:
    app: toposervice
  ports:
    - port: 8080
      protocol: TCP
      name: toposervice-port
  
  