---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1 
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: franrobles8/server:v1.0
        ports:
        - containerPort: 3000
        env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_DB
            value: eoloplantsDB
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASS
            value: password
          - name: RABBITMQ_URL
            value: amqp://root:password@rabbitmq
