---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  type: LoadBalancer
  ports:
  - name: server-port
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: server
  