---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherservice-deployment
spec:
  selector:
    matchLabels:
      app: weatherservice
  replicas: 1 
  template:
    metadata:
      labels:
        app: weatherservice
    spec:
      containers:
      - name: weatherservice
        image: franrobles8/weatherservice:v1.0
        ports:
        - containerPort: 9090
        env:
          - name: GRPC_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: GRPC_PORT
            value: "9090"
