---
apiVersion: v1
kind: Service
metadata:
  name: weatherservice
  labels:
    app: weatherservice
spec:
  type: ClusterIP
  selector:
    app: weatherservice
  ports:
    - port: 9090
      protocol: TCP
      name: weatherservice-port
  
  