---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner-deployment
spec:
  selector:
    matchLabels:
      app: planner
  replicas: 1 
  template:
    metadata:
      labels:
        app: planner
    spec:
      containers:
      - name: planner
        image: franrobles8/planner:v1.0
        ports:
        - containerPort: 8080
        env:
          - name: TOPO_HOST
            value: toposervice
          - name: TOPO_PORT
            value: "8080"
          - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
            value: static://weatherservice:9090
          - name: SPRING_RABBITMQ_HOST
            value: rabbitmq
          - name: SPRING_RABBITMQ_PORT
            value: "5672"
          - name: SPRING_RABBITMQ_USERNAME
            value: root
          - name: SPRING_RABBITMQ_PASSWORD
            value: password
