---
apiVersion: v1
kind: Service
metadata:
  name: planner
  labels:
    app: planner
spec:
  type: ClusterIP
  selector:
    app: planner
  ports:
    - port: 8080
      protocol: TCP
      name: planner-port
  
  