---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      protocol: TCP
      name: mongodb-port
    - port: 27018
      protocol: TCP
      name: mongodb-port-2
    - port: 27019
      protocol: TCP
      name: mongodb-port-3
  
  